package entidades;
// Generated 18-jul-2019 4:13:52 by Hibernate Tools 4.3.1



/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private int idsexo;
     private Mascota mascota;
     private String descripcion;
     private String estado;

    public Sexo() {
    }

	
    public Sexo(int idsexo, String descripcion, String estado) {
        this.idsexo = idsexo;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Sexo(int idsexo, Mascota mascota, String descripcion, String estado) {
       this.idsexo = idsexo;
       this.mascota = mascota;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdsexo() {
        return this.idsexo;
    }
    
    public void setIdsexo(int idsexo) {
        this.idsexo = idsexo;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


